/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.employeeManagementSystem.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rw.gov.employeeManagementSystem.dao.DepartmentDao;
import rw.gov.employeeManagementSystem.model.Department;

/**
 *
 * @author ZIPTECH LTD
 */
public class DepartmentView extends javax.swing.JFrame {

    /**
     * Creates new form Department
     */
    public DepartmentView() {
        initComponents();
        allDepartmentRetrived();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeBtn = new javax.swing.JButton();
        jobsBn = new javax.swing.JButton();
        salariesBtn = new javax.swing.JButton();
        department1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        employeeBtn1 = new javax.swing.JButton();
        salariesBtn1 = new javax.swing.JButton();
        jobBtn = new javax.swing.JButton();
        department = new javax.swing.JButton();
        department3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dptName = new javax.swing.JTextField();
        addDptBtn = new javax.swing.JButton();
        updateDptBtn1 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        allDepartment = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        summaryBtn = new javax.swing.JButton();

        employeeBtn.setBackground(new java.awt.Color(255, 255, 255));
        employeeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeBtn.setText("Employee");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        jobsBn.setBackground(new java.awt.Color(255, 255, 255));
        jobsBn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jobsBn.setText("Jobs");
        jobsBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsBnActionPerformed(evt);
            }
        });

        salariesBtn.setBackground(new java.awt.Color(255, 255, 255));
        salariesBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salariesBtn.setText("Salaries");
        salariesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salariesBtnActionPerformed(evt);
            }
        });

        department1.setBackground(new java.awt.Color(255, 255, 255));
        department1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department1.setText("Departments");
        department1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 204, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeBtn1.setBackground(new java.awt.Color(255, 255, 255));
        employeeBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeBtn1.setForeground(new java.awt.Color(0, 153, 153));
        employeeBtn1.setText("Employee");
        employeeBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        employeeBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtn1ActionPerformed(evt);
            }
        });
        jPanel6.add(employeeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 229, 272, 40));

        salariesBtn1.setBackground(new java.awt.Color(255, 255, 255));
        salariesBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salariesBtn1.setForeground(new java.awt.Color(0, 153, 153));
        salariesBtn1.setText("Salaries");
        salariesBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        salariesBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salariesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salariesBtn1ActionPerformed(evt);
            }
        });
        jPanel6.add(salariesBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 272, 37));

        jobBtn.setBackground(new java.awt.Color(255, 255, 255));
        jobBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jobBtn.setForeground(new java.awt.Color(0, 153, 153));
        jobBtn.setText("Jobs");
        jobBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        jobBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobBtnActionPerformed(evt);
            }
        });
        jPanel6.add(jobBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 318, 272, 39));

        department.setBackground(new java.awt.Color(255, 255, 255));
        department.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department.setForeground(new java.awt.Color(0, 153, 153));
        department.setText("Departments");
        department.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        department.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel6.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 272, 37));

        department3.setBackground(new java.awt.Color(255, 255, 255));
        department3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department3.setForeground(new java.awt.Color(0, 153, 153));
        department3.setText("Home");
        department3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        department3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department3ActionPerformed(evt);
            }
        });
        jPanel6.add(department3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 272, 37));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel6.setText("Departments");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Add Department");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Department Name:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));
        jPanel3.add(dptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 62, 163, 28));

        addDptBtn.setBackground(new java.awt.Color(0, 51, 255));
        addDptBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addDptBtn.setText("+ Add");
        addDptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDptBtnActionPerformed(evt);
            }
        });
        jPanel3.add(addDptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        updateDptBtn1.setBackground(new java.awt.Color(0, 153, 0));
        updateDptBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateDptBtn1.setText("Update");
        updateDptBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDptBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(updateDptBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        deleteBtn.setBackground(new java.awt.Color(204, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 707, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("search By Name");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        allDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allDepartment);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("All Departments");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel6))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchBtn)
                                    .addGap(156, 156, 156)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchBtn))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 650, 630));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("     EPMS");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        summaryBtn.setBackground(new java.awt.Color(255, 255, 255));
        summaryBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        summaryBtn.setForeground(new java.awt.Color(0, 153, 153));
        summaryBtn.setText("Summary");
        summaryBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        summaryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        summaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBtnActionPerformed(evt);
            }
        });
        jPanel6.add(summaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 272, 37));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void jobsBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsBnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobsBnActionPerformed

    private void salariesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salariesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salariesBtnActionPerformed

    private void department1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department1ActionPerformed
        DepartmentView department = new DepartmentView();
        department.show();

        dispose();
    }//GEN-LAST:event_department1ActionPerformed

    private void allDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allDepartmentMouseClicked

        int selectedRow = allDepartment.getSelectedRow();
        DefaultTableModel tbModel = (DefaultTableModel) allDepartment.getModel();
        //        int theId = Integer.parseInt(tbModel.getValueAt(selectedRow, 0).toString());
        dptName.setText(tbModel.getValueAt(selectedRow, 1).toString());
//        addDptBtn.enable(false);

    }//GEN-LAST:event_allDepartmentMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        DepartmentDao dptDao = new DepartmentDao();
        DefaultTableModel tbModel = (DefaultTableModel) allDepartment.getModel();

        try {
            if (searchTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Search Can't be Empty");
                searchTxt.setText("");
            } else {
                ResultSet rs = dptDao.searchDepartments(searchTxt.getText());
                tbModel.setRowCount(0);
                if (rs.isBeforeFirst()) {
                    while (rs.next()) {
                        String id = rs.getString("id");
                        String name = rs.getString("name");
                        String tData[] = {id, name};

                        tbModel.addRow(tData);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Results");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (allDepartment.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select Something to Delete First");
        } else if (dptName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Department Name can't Be Empty");
        } else {
            int choice = JOptionPane.showConfirmDialog(null, "Are U sure To delete", "confirm", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int selectedRow = allDepartment.getSelectedRow();
                DefaultTableModel tbModel = (DefaultTableModel) allDepartment.getModel();
                int thId = Integer.parseInt(tbModel.getValueAt(selectedRow, 0).toString());

                DepartmentDao dptDao = new DepartmentDao();
                Integer rowAffected = dptDao.delete(thId);

                if (rowAffected != null) {
                    JOptionPane.showMessageDialog(this, "Data Deleted");
                    dptName.setText("");
                    allDepartmentRetrived();
                } else {
                    JOptionPane.showMessageDialog(this, "Data not Deleted");
                }
            }

        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateDptBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDptBtn1ActionPerformed
        if (allDepartment.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select Something to Update First");
        } else if (dptName.getText().trim().isEmpty() || dptName.getText().length() < 4) {
            JOptionPane.showMessageDialog(this, "Name not Valid \nMake sure not Empty \nMake sure not less that 4 char");
        } else {
            int selectedRow = allDepartment.getSelectedRow();
            DefaultTableModel tbModel = (DefaultTableModel) allDepartment.getModel();
            Department newDepartment = new Department();

            int thId = Integer.parseInt(tbModel.getValueAt(selectedRow, 0).toString());
            newDepartment.setId(thId);
            newDepartment.setName(dptName.getText());

            DepartmentDao dptDao = new DepartmentDao();
            Integer rowAffected = dptDao.update(newDepartment);

            if (rowAffected != null) {
                JOptionPane.showMessageDialog(this, "Data updated");
                dptName.setText("");
                allDepartmentRetrived();
            } else {
                JOptionPane.showMessageDialog(this, "Data not updated");
            }
        }
    }//GEN-LAST:event_updateDptBtn1ActionPerformed

    private void addDptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDptBtnActionPerformed
        if (dptName.getText().trim().isEmpty() || dptName.getText().length() < 4) {
            JOptionPane.showMessageDialog(this, "Name not Valid \nMake sure not Empty \nMake sure not less that 4 char");
        } else {
            Department newDepartment = new Department();
            newDepartment.setName(dptName.getText());

            DepartmentDao newDepartmentDao = new DepartmentDao();
            Integer rowsAffected = newDepartmentDao.register(newDepartment);

            if (rowsAffected != null) {
                JOptionPane.showMessageDialog(this, "Data Saved");
                dptName.setText("");
                allDepartmentRetrived();
            } else {
                JOptionPane.showMessageDialog(this, "Data not Saved");
            }
        }

    }//GEN-LAST:event_addDptBtnActionPerformed

    private void department3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department3ActionPerformed
        Home home = new Home();
        home.show();

        dispose();
    }//GEN-LAST:event_department3ActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        DepartmentView department = new DepartmentView();
        department.show();

        dispose();
    }//GEN-LAST:event_departmentActionPerformed

    private void jobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobBtnActionPerformed
        JobView job = new JobView();
        job.show();

        dispose();
    }//GEN-LAST:event_jobBtnActionPerformed

    private void salariesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salariesBtn1ActionPerformed
        SalaryView salary = new SalaryView();
        salary.show();

        dispose();
    }//GEN-LAST:event_salariesBtn1ActionPerformed

    private void employeeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtn1ActionPerformed
        EmployeeView empView = new EmployeeView();
        empView.show();

        dispose();
    }//GEN-LAST:event_employeeBtn1ActionPerformed

    private void summaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBtnActionPerformed
        Summary summary = new Summary();
        summary.show();

        dispose();
    }//GEN-LAST:event_summaryBtnActionPerformed

    private void allDepartmentRetrived() {
        DepartmentDao dptDao = new DepartmentDao();
        DefaultTableModel tbModel = (DefaultTableModel) allDepartment.getModel();
        ResultSet rs = dptDao.allDepartments();
        tbModel.setRowCount(0);
        try {
            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("name");
                String tData[] = {id, name};

                tbModel.addRow(tData);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDptBtn;
    private javax.swing.JTable allDepartment;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton department;
    private javax.swing.JButton department1;
    private javax.swing.JButton department3;
    private javax.swing.JTextField dptName;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton employeeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jobBtn;
    private javax.swing.JButton jobsBn;
    private javax.swing.JButton salariesBtn;
    private javax.swing.JButton salariesBtn1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton summaryBtn;
    private javax.swing.JButton updateDptBtn1;
    // End of variables declaration//GEN-END:variables
}
