/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.employeeManagementSystem.view;

/**
 *
 * @author ZIPTECH LTD
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        employeeBtn = new javax.swing.JButton();
        salariesBtn = new javax.swing.JButton();
        jobBtn = new javax.swing.JButton();
        department = new javax.swing.JButton();
        summaryBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        department2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeBtn.setBackground(new java.awt.Color(255, 255, 255));
        employeeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeBtn.setForeground(new java.awt.Color(0, 153, 153));
        employeeBtn.setText("Employee");
        employeeBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        employeeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(employeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 229, 272, 40));

        salariesBtn.setBackground(new java.awt.Color(255, 255, 255));
        salariesBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salariesBtn.setForeground(new java.awt.Color(0, 153, 153));
        salariesBtn.setText("Salaries");
        salariesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        salariesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salariesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salariesBtnActionPerformed(evt);
            }
        });
        jPanel2.add(salariesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 272, 37));

        jobBtn.setBackground(new java.awt.Color(255, 255, 255));
        jobBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jobBtn.setForeground(new java.awt.Color(0, 153, 153));
        jobBtn.setText("Jobs");
        jobBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        jobBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jobBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 318, 272, 39));

        department.setBackground(new java.awt.Color(255, 255, 255));
        department.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department.setForeground(new java.awt.Color(0, 153, 153));
        department.setText("Departments");
        department.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        department.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel2.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 272, 37));

        summaryBtn.setBackground(new java.awt.Color(255, 255, 255));
        summaryBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        summaryBtn.setForeground(new java.awt.Color(0, 153, 153));
        summaryBtn.setText("Summary");
        summaryBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        summaryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        summaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBtnActionPerformed(evt);
            }
        });
        jPanel2.add(summaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 272, 37));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel3.setText("Employee Management System-Home");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 770, 630));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("     EPMS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        department2.setBackground(new java.awt.Color(255, 255, 255));
        department2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department2.setForeground(new java.awt.Color(0, 153, 153));
        department2.setText("Home");
        department2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        department2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department2ActionPerformed(evt);
            }
        });
        jPanel2.add(department2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 272, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void summaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBtnActionPerformed
        Summary summary = new Summary();
        summary.show();

        dispose();
    }//GEN-LAST:event_summaryBtnActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        DepartmentView department = new DepartmentView();
        department.show();

        dispose();
    }//GEN-LAST:event_departmentActionPerformed

    private void jobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobBtnActionPerformed
        JobView job = new JobView();
        job.show();

        dispose();
    }//GEN-LAST:event_jobBtnActionPerformed

    private void salariesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salariesBtnActionPerformed
        SalaryView salary = new SalaryView();
        salary.show();

        dispose();
    }//GEN-LAST:event_salariesBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        EmployeeView empView = new EmployeeView();
        empView.show();

        dispose();
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void department2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_department2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton department;
    private javax.swing.JButton department2;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jobBtn;
    private javax.swing.JButton salariesBtn;
    private javax.swing.JButton summaryBtn;
    // End of variables declaration//GEN-END:variables
}
