/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.employeeManagementSystem.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rw.gov.employeeManagementSystem.dao.JobDao;
import rw.gov.employeeManagementSystem.dao.SalaryDao;
import rw.gov.employeeManagementSystem.model.Salary;

/**
 *
 * @author ZIPTECH LTD
 */
public class SalaryView extends javax.swing.JFrame {

    /**
     * Creates new form SalaryView
     */
    public SalaryView() {
        initComponents();
        allSalaryRetrived();
        fillCombBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        employeeBtn = new javax.swing.JButton();
        salariesBtn = new javax.swing.JButton();
        jobBtn = new javax.swing.JButton();
        department = new javax.swing.JButton();
        department1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addSalary1 = new javax.swing.JButton();
        updateSalary = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        bonus = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        JName = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        allsalaries = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        summaryBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeBtn.setBackground(new java.awt.Color(255, 255, 255));
        employeeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeBtn.setForeground(new java.awt.Color(0, 153, 153));
        employeeBtn.setText("Employee");
        employeeBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        employeeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(employeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 229, 272, 40));

        salariesBtn.setBackground(new java.awt.Color(255, 255, 255));
        salariesBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salariesBtn.setForeground(new java.awt.Color(0, 153, 153));
        salariesBtn.setText("Salaries");
        salariesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        salariesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salariesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salariesBtnActionPerformed(evt);
            }
        });
        jPanel3.add(salariesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 272, 37));

        jobBtn.setBackground(new java.awt.Color(255, 255, 255));
        jobBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jobBtn.setForeground(new java.awt.Color(0, 153, 153));
        jobBtn.setText("Jobs");
        jobBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        jobBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobBtnActionPerformed(evt);
            }
        });
        jPanel3.add(jobBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 318, 272, 39));

        department.setBackground(new java.awt.Color(255, 255, 255));
        department.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department.setForeground(new java.awt.Color(0, 153, 153));
        department.setText("Departments");
        department.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        department.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel3.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 272, 37));

        department1.setBackground(new java.awt.Color(255, 255, 255));
        department1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department1.setForeground(new java.awt.Color(0, 153, 153));
        department1.setText("Home");
        department1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        department1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department1ActionPerformed(evt);
            }
        });
        jPanel3.add(department1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 272, 37));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel4.setText("Salaries");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Add Salary");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Job Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Amount");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Bonus");

        addSalary1.setBackground(new java.awt.Color(0, 51, 255));
        addSalary1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addSalary1.setText("+ Add");
        addSalary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalary1ActionPerformed(evt);
            }
        });

        updateSalary.setBackground(new java.awt.Color(0, 153, 0));
        updateSalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateSalary.setText("Update");
        updateSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSalaryActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(204, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        JName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Job --" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addComponent(addSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(updateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        allsalaries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Job", "Amount", "Anual", "Bonus"
            }
        ));
        allsalaries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allsalariesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allsalaries);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search By Amount ");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("All Salary");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 770, 630));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("     EPMS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        summaryBtn1.setBackground(new java.awt.Color(255, 255, 255));
        summaryBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        summaryBtn1.setForeground(new java.awt.Color(0, 153, 153));
        summaryBtn1.setText("Summary");
        summaryBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        summaryBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        summaryBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(summaryBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 272, 37));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSalaryActionPerformed

        if (amount.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount Can't be empty");
        } else if (bonus.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bonus Can't be empty");
        } else {
            int rowSelected = allsalaries.getSelectedRow();
            DefaultTableModel tbModel = (DefaultTableModel) allsalaries.getModel();

            int theId = Integer.parseInt(tbModel.getValueAt(rowSelected, 0).toString());
//            int theamount = Integer.parseInt(tbModel.getValueAt(rowSelected, 2).toString());
//            int theanual = theamount * 12;
//            int thebonus = Integer.parseInt(tbModel.getValueAt(rowSelected, 4).toString());
////            int thejobId = Integer.parseInt(tbModel.getValueAt(rowSelected, 1).toString());

            Salary theSalary = new Salary();
            SalaryDao theSalaryDao = new SalaryDao();

            theSalary.setJobName(JName.getSelectedItem().toString());
            theSalary.setAmount(Integer.parseInt(amount.getText()));
            theSalary.setAnual(Integer.parseInt(amount.getText()) * 12);
            theSalary.setBonus(Integer.parseInt(bonus.getText()));
            theSalary.setId(theId);

            Integer rowAffected = theSalaryDao.update(theSalary);
            if (rowAffected != null) {
                JOptionPane.showMessageDialog(this, "Salary Updated");
                JName.setSelectedIndex(0);
                amount.setText("");
                bonus.setText("");
                allSalaryRetrived();
            } else {
                JOptionPane.showMessageDialog(this, "salary not saved");
            }
        }

    }//GEN-LAST:event_updateSalaryActionPerformed
    private void allSalaryRetrived() {
        SalaryDao saleryDao = new SalaryDao();

        ResultSet rs = saleryDao.allSalaries();
        DefaultTableModel tbModel = (DefaultTableModel) allsalaries.getModel();
        tbModel.setRowCount(0);

        try {
            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("job_name");
                String amount = rs.getString("amount");
                String anual = rs.getString("anual");
                String bonus = rs.getString("bonus");
//                String total = Integer.parseInt(anual) + Integer.parseInt(bonus);

                String tData[] = {id, name, amount, anual, bonus};

                tbModel.addRow(tData);

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void addSalary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalary1ActionPerformed
        if (amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount Can't be empty");
        } else if (bonus.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bonus Can't be empty");
        } else {
            try {
                Salary newSalary = new Salary();

                
                int theamount = Integer.parseInt(amount.getText());
                int theanual = theamount * 12;
                int thebonus = Integer.parseInt(bonus.getText());

                newSalary.setJobName(JName.getSelectedItem().toString());
                newSalary.setAmount(theamount);
                newSalary.setAnual(theanual);
                newSalary.setBonus(thebonus);

                SalaryDao newSalaryDao = new SalaryDao();
                Integer rowAffected = newSalaryDao.register(newSalary);

                if (rowAffected != null) {
                    JOptionPane.showMessageDialog(this, "Salary Added");
                    JName.setSelectedIndex(0);
                    amount.setText("");
                    bonus.setText("");
                    allSalaryRetrived();
                } else {
                    JOptionPane.showMessageDialog(this, "salary not added");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_addSalary1ActionPerformed


    private void allsalariesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allsalariesMouseClicked
        int rowSelected = allsalaries.getSelectedRow();
        DefaultTableModel tbModel = (DefaultTableModel) allsalaries.getModel();
        JName.setSelectedItem(tbModel.getValueAt(rowSelected, 2).toString());
        amount.setText(tbModel.getValueAt(rowSelected, 2).toString());
        bonus.setText(tbModel.getValueAt(rowSelected, 4).toString());
    }//GEN-LAST:event_allsalariesMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        int choice = JOptionPane.showConfirmDialog(null, "Are U sure To delete", "confirm", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {

            int rowSelected = allsalaries.getSelectedRow();
            DefaultTableModel tbModel = (DefaultTableModel) allsalaries.getModel();
            int theId = Integer.parseInt(tbModel.getValueAt(rowSelected, 0).toString());

            SalaryDao newSalaryDao = new SalaryDao();
            Integer rowAffected = newSalaryDao.delete(theId);

            if (rowAffected != null) {
                JOptionPane.showMessageDialog(this, "Salary Deleted");
                JName.setSelectedIndex(0);
                amount.setText("");
                bonus.setText("");
                allSalaryRetrived();
            } else {
                JOptionPane.showMessageDialog(this, "salary not Deleted");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        SalaryDao salaryDao = new SalaryDao();
        DefaultTableModel tbModel = (DefaultTableModel) allsalaries.getModel();
        tbModel.setRowCount(0);

        try {
            if (searchTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Search Can't be Empty");
                searchTxt.setText("");
            } else {
                tbModel.setRowCount(0);
                ResultSet rs = salaryDao.searchSalary(searchTxt.getText());
                if (rs.isBeforeFirst()) {
                    while (rs.next()) {
                        String id = rs.getString("id");
                        String name = rs.getString("Job_name");
                        String amount = rs.getString("amount");
                        String anual = rs.getString("anual");
                        String bonus = rs.getString("bonus");

                        String tData[] = {id, name, amount, anual, bonus};
                        tbModel.addRow(tData);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Results");
                }

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        EmployeeView empView = new EmployeeView();
        empView.show();

        dispose();
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void salariesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salariesBtnActionPerformed
        SalaryView salary = new SalaryView();
        salary.show();

        dispose();
    }//GEN-LAST:event_salariesBtnActionPerformed

    private void jobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobBtnActionPerformed
        JobView job = new JobView();
        job.show();

        dispose();
    }//GEN-LAST:event_jobBtnActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        DepartmentView department = new DepartmentView();
        department.show();

        dispose();
    }//GEN-LAST:event_departmentActionPerformed

    private void department1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department1ActionPerformed
        Home home = new Home();
        home.show();

        dispose();
    }//GEN-LAST:event_department1ActionPerformed

    private void summaryBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBtn1ActionPerformed
        Summary summary = new Summary();
        summary.show();

        dispose();
    }//GEN-LAST:event_summaryBtn1ActionPerformed

    private void fillCombBox() {
        JobDao jobDao = new JobDao();
        ResultSet rs = jobDao.allJobs();
        try {
            while(rs.next()){
            JName.addItem(rs.getString("name"));   
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JName;
    private javax.swing.JButton addSalary1;
    private javax.swing.JTable allsalaries;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField bonus;
    private javax.swing.JButton delete;
    private javax.swing.JButton department;
    private javax.swing.JButton department1;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jobBtn;
    private javax.swing.JButton salariesBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton summaryBtn;
    private javax.swing.JButton summaryBtn1;
    private javax.swing.JButton updateSalary;
    // End of variables declaration//GEN-END:variables
}
